CREATE TABLE gituser
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name       VARCHAR(255),
    email      VARCHAR(255),
    avatar_url VARCHAR(255),
    CONSTRAINT pk_gituser PRIMARY KEY (id),
    CONSTRAINT uc_gituser_email UNIQUE (email)
);
